### PR TITLE
Update rnc specification to allow crash_kernel values list

### PR DESCRIPTION
**Pull request by imobach**
@schubi2 I've tested manually that it can be converted to rng (using trang) but I'm not sure about how to improve testing on that.

BTW, it should be reflected in AutoYaST documentation.

This PR should be merged when as part of bugfix for https://bugzilla.suse.com/show_bug.cgi?id=882082.

### CODE REVIEW

**Comment by schubi2** [comment]
So, the changelog and version will be handled in another PR ? LGTM
Please send me the changed documentation, in order to submit it.

**Comment by imobach** [comment]
@schubi2 Thanks for review. You're right. Thinking about it, I'll need to rebase this PR, so I'll handle them changelog and version. Of I'll send you the updated documentation as soon as I merge these changes.

**Comment by ancorgs** [comment]
LGTM, as it was already reviewed by @schubi2

**Comment by imobach** [comment]
@ancorgs Yes, but I've updated the changelog after that.

**Comment by ancorgs** [comment]
Yes, I noticed it. Hence the LGTM :-)

**Pull request merged**
