### PR TITLE
Implement KDUMP_AUTO_RESIZE

### PR DESCRIPTION
**Pull request by ptesarik**
[Kdump-1.0.1](https://github.com/openSUSE/kdump) adds a [new option to resize the crash kernel reservation automatically at boot](https://github.com/openSUSE/kdump/commit/60de244b333cc036c1d9d071e02fb4dbd9dd6e9a). It's non-trivial to use it properly, but the YaST module can be of great help!

This would have been the ultimate goal of [jsc#SLE-18441](https://jira.suse.com/browse/SLE-18441) "_Auto scale crashkernel size with hardware changes_", but yeah, I know it's probably too late now. If nothing else, Tumbleweed may benefit from this work.

### CODE REVIEW

**Comment by ptesarik** [comment]
I appreciate any suggestions how the test cases can be fixed.

For the default installation, it is expected that the values are different, because I'd like to enable {{KDUMP_AUTO_RESIZE}}. I can have a look at those failing tests.

But I don't have any clue about the autoyast failure. I think that auto-resize should be disabled if the autoyast profile specifies an explicit value, and there should be a way to disable auto-resize even if no explicit value is specified, but that's starting to be too much for my poor yast development skills.

**Comment by ptesarik** [comment]
> I appreciate any suggestions how the test cases can be fixed.

Never mind, I think I have figured it out. See my commit b391fd1 (last on this branch).

**Comment by ptesarik** [comment]
FYI I've rebased all commits once again, adding my correct GPG signature.

**Review by joseivanlopez — COMMENTED** [review]
Thanks Petr for this PR! To be honest, I don't know this YaST module too much. Anyway, having a look to the code and tests, it looks quite ok to me. 

Acoording to the tests, I see this new setting should also work with AutoYaST. In that case, you have to add the setting to the scheme definition here https://github.com/yast/yast-kdump/blob/master/src/autoyast-rnc/kdump.rnc#L32.

Moreover, it would be great to open a new PR for the AutoYaST documentation in order to document this new setting: https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-configuration-installation-options.html#CreateProfile-kdump-saving-summary

Maybe @imobachgs as AutoYaST expert could suggest some more things to adapt.

**Comment by imobachgs** [comment]
> Maybe @imobachgs as AutoYaST expert could suggest some more things to adapt.

Yes, please, add the `KDUMP_AUTO_RESIZE` element to the rnc file if possible. I will take care of adapting `yast2-schema` and updating the docs.

**Comment by jreidinger** [comment]
@ptesarik I see it does not move for two weeks, do you need some help with implementing autoyast support? If so, feel free to contact me on IRC or slack.

**Comment by ptesarik** [comment]
Er, I have found some time to look at this PR again. So, I added one line to the rnc file in commit 99eb3ba, but now I feel stupid. Were you indeed waiting just for this one line?

**Comment by jreidinger** [comment]
@ptesarik sorry, it gets a bit out of my radar. it is really a bit too late for SP4, but master is open for SP5 and TW. So far it looks good for me. Just please add entry to changelog and bump version and we can merge it.

Thanks and sorry

**Comment by dgdavid** [comment]
Hi @ptesarik, @jreidinger 

How can I help for moving the PR on and get it merged?

**Comment by jreidinger** [comment]
@dgdavid well, as said, if you solve conflicts that appear meanwhile and add changelog entry and bump version, then nothing is in the way to merge it

**Comment by dgdavid** [comment]
> @dgdavid well, as said, if you solve conflicts that appear meanwhile and add changelog entry and bump version, then nothing is in the way to merge it

Ok, I'll try it during the morning. Hope @ptesarik don't mind.

**Comment by dgdavid** [comment]
Ok, I've tried it. But it needs someone else review :)

All existing test are passing, but we should ensure that intended changes are ok after merging conflicts found because of https://github.com/yast/yast-kdump/pull/126

@ptesarik, @imobachgs, friendly ping :wink:

**Review by jreidinger — APPROVED** [review]

**Comment by dgdavid** [comment]
Thanks for the re-review @jreidinger.

I'll merge it now :crossed_fingers:

**Pull request merged**
